import { Note } from "../../src";
import { runStrumTests } from "../helpers";

describe("SlideTransformer.strum", () => {
  runStrumTests([
    {
      notes: [
        { pitch: 1, start: 0 },
        { pitch: 2, start: 0 },
        { pitch: 3, start: 0 },
        { pitch: 4, start: 0 },
        { pitch: 5, start: 0 },
      ],
      range: 1,
      amount: 1,
      anchor: "min",
      unlockEnd: true,
      expected: [0, 0.25, 0.5, 0.75, 1],
    },
    {
      notes: [
        { pitch: 1, start: 0 },
        { pitch: 10, start: 0 },
        { pitch: 30, start: 0 },
        { pitch: 60, start: 0 },
        { pitch: 120, start: 0 },
      ],
      range: 1,
      amount: 1,
      anchor: "min",
      unlockEnd: true,
      expected: [0, 0.25, 0.5, 0.75, 1],
    },
    {
      notes: [
        { pitch: 1, start: 0 },
        { pitch: 2, start: 1 },
        { pitch: 3, start: 2 },
        { pitch: 4, start: 3 },
        { pitch: 5, start: 4 },
      ],
      range: 1,
      amount: 1,
      anchor: "min",
      unlockEnd: true,
      expected: [0, 1.25, 2.5, 3.75, 5],
    },
    {
      notes: [
        { pitch: 1, start: 2 },
        { pitch: 2, start: 2 },
        { pitch: 3, start: 2 },
        { pitch: 4, start: 2 },
        { pitch: 5, start: 2 },
      ],
      range: 2,
      amount: -1,
      anchor: "min",
      unlockEnd: true,
      expected: [2, 1.5, 1, 0.5, 0],
    },
    {
      notes: [
        { pitch: 1, start: 0 },
        { pitch: 2, start: 0 },
        { pitch: 3, start: 0 },
        { pitch: 4, start: 0 },
        { pitch: 5, start: 0 },
      ],
      range: 1,
      amount: 1,
      anchor: "max",
      unlockEnd: true,
      expected: [1, 0.75, 0.5, 0.25, 0],
    },
    {
      notes: [
        { pitch: 1, start: 2 },
        { pitch: 2, start: 2 },
        { pitch: 3, start: 2 },
        { pitch: 4, start: 2 },
        { pitch: 5, start: 2 },
      ],
      range: 4,
      amount: 1,
      anchor: "mid",
      unlockEnd: true,
      expected: [0, 1, 2, 3, 4],
    },
    {
      notes: [
        { pitch: 1, start: 2 },
        { pitch: 2, start: 2 },
        { pitch: 3, start: 2 },
        { pitch: 4, start: 2 },
        { pitch: 5, start: 2 },
      ],
      range: 4,
      amount: -1,
      anchor: "mid",
      unlockEnd: true,
      expected: [4, 3, 2, 1, 0],
    },
    {
      notes: [
        { pitch: 1, start: 0, duration: 2 },
        { pitch: 2, start: 0, duration: 2 },
        { pitch: 3, start: 0, duration: 2 },
        { pitch: 4, start: 0, duration: 2 },
        { pitch: 5, start: 0, duration: 2 },
      ],
      range: 1,
      amount: 1,
      anchor: "min",
      unlockEnd: false,
      expected: [
        { start: 0, duration: 2 },
        { start: 0.25, duration: 1.75 },
        { start: 0.5, duration: 1.5 },
        { start: 0.75, duration: 1.25 },
        { start: 1, duration: 1 }
      ],
    },
    {
      notes: [
        { pitch: 1, start: 0, duration: 1 },
        { pitch: 2, start: 0, duration: 1 },
        { pitch: 3, start: 0, duration: 1 },
        { pitch: 4, start: 0, duration: 1 },
        { pitch: 5, start: 0, duration: 1 },
      ],
      range: 1,
      amount: 1,
      anchor: "min",
      unlockEnd: false,
      expected: [
        { start: 0, duration: 1 },
        { start: 0.25, duration: 0.75 },
        { start: 0.5, duration: 0.5 },
        { start: 0.75, duration: 0.25 },
        { start: 1 - Note.MIN_DURATION, duration: Note.MIN_DURATION },
      ],
    },
    {
      notes: [
        { pitch: 1, start: 0, duration: 1 },
        { pitch: 2, start: 0.5, duration: 0.5 },
        { pitch: 3, start: 1, duration: 1 },
      ],
      range: 1,
      amount: 1,
      anchor: "min",
      unlockEnd: false,
      expected: [
        { start: 0, duration: 1 },
        { start: 1 - Note.MIN_DURATION, duration: Note.MIN_DURATION },
        { start: 2 - Note.MIN_DURATION, duration: Note.MIN_DURATION },
      ],
    },
    {
      notes: [
        { pitch: 1, start: 0 },
        { pitch: 2, start: 0 },
        { pitch: 3, start: 0 },
        { pitch: 4, start: 0 },
        { pitch: 5, start: 0 },
      ],
      range: 1,
      amount: 1,
      anchor: "min",
      unlockEnd: true,
      expected: [0, 0.25 ** 2, 0.5 ** 2, 0.75 ** 2, 1],
      tension: 2,
    },
    {
      notes: [
        { pitch: 1, start: 0 },
        { pitch: 2, start: 0 },
        { pitch: 3, start: 0 },
        { pitch: 4, start: 0 },
        { pitch: 5, start: 0 },
      ],
      range: 1,
      amount: 1,
      anchor: "min",
      unlockEnd: true,
      expected: [0, 0.25 ** 0.75, 0.5 ** 0.75, 0.75 ** 0.75, 1],
      tension: 0.75,
    },
    {
      notes: [
        { pitch: 1, start: 0 },
        { pitch: 2, start: 0 },
        { pitch: 3, start: 0 },
        { pitch: 4, start: 0 },
        { pitch: 5, start: 0 },
      ],
      clip: { start: 0, end: 1 },
      range: 1,
      amount: 1.5,
      anchor: "min",
      unlockEnd: true,
      edgeBehavior: "clamp",
      expected: [
        0, 0.375, 0.75, 1 - Note.MIN_DURATION, 1 - Note.MIN_DURATION,
      ],
    },
    {
      notes: [
        { pitch: 1, start: 0 },
        { pitch: 2, start: 0 },
        { pitch: 3, start: 0 },
        { pitch: 4, start: 0 },
        { pitch: 5, start: 0 },
      ],
      range: 1,
      amount: 1,
      anchor: "min",
      unlockEnd: false,
      edgeBehavior: "clamp",
      expected: [
        { start: 0, duration: 1 },
        { start: 0.25, duration: 0.75 },
        { start: 0.5, duration: 0.5 },
        { start: 0.75, duration: 0.25 },
        { start: 1 - Note.MIN_DURATION, duration: Note.MIN_DURATION },
      ],
    },
    {
      notes: [
        { pitch: 1, start: 1 },
        { pitch: 2, start: 1 },
        { pitch: 3, start: 1 },
        { pitch: 4, start: 1 },
        { pitch: 5, start: 1 },
      ],
      range: 1,
      amount: -1.5,
      anchor: "min",
      unlockEnd: false,
      edgeBehavior: "clamp",
      expected: [
        { start: 1, duration: 1 },
        { start: 0.625, duration: 1.375 },
        { start: 0.25, duration: 1.75 },
        { start: 0, duration: 2 },
        { start: 0, duration: 2 },
      ],
    },
    {
      notes: [
        { pitch: 1, start: 0 },
        { pitch: 2, start: 0 },
        { pitch: 3, start: 0 },
        { pitch: 4, start: 0 },
        { pitch: 5, start: 0 },
      ],
      clip: { start: 0, end: 1 },
      range: 2,
      amount: 1.5,
      anchor: "min",
      unlockEnd: true,
      edgeBehavior: "reflect",
      expected: [
        0, 0.75, 0.5, 0.25, 1 - Note.MIN_DURATION,
      ],
    },
    {
      notes: [
        { pitch: 1, start: 0 },
        { pitch: 2, start: 0 },
        { pitch: 3, start: 0 },
        { pitch: 4, start: 0 },
        { pitch: 5, start: 0 },
      ],
      range: 2,
      amount: 1,
      anchor: "min",
      unlockEnd: false,
      edgeBehavior: "reflect",
      expected: [
        { start: 0, duration: 1 },
        { start: 0.5, duration: 0.5 },
        { start: 1 - Note.MIN_DURATION, duration: Note.MIN_DURATION },
        { start: 0.5, duration: 0.5 },
        { start: 0, duration: 1 },
      ],
    },
    {
      notes: [
        { pitch: 1, start: 1 },
        { pitch: 2, start: 1 },
        { pitch: 3, start: 1 },
        { pitch: 4, start: 1 },
        { pitch: 5, start: 1 },
      ],
      range: 1,
      amount: -1.5,
      anchor: "min",
      unlockEnd: false,
      edgeBehavior: "reflect",
      expected: [
        { start: 1, duration: 1 },
        { start: 0.625, duration: 1.375 },
        { start: 0.25, duration: 1.75 },
        { start: 0.125, duration: 1.875 },
        { start: 0.5, duration: 1.5 },
      ],
    },
    {
      notes: [
        { pitch: 1, start: 0 },
        { pitch: 2, start: 0 },
        { pitch: 3, start: 0 },
        { pitch: 4, start: 0 },
        { pitch: 5, start: 0 },
      ],
      clip: { start: 0, end: 1 },
      range: 2,
      amount: 1,
      anchor: "min",
      unlockEnd: true,
      edgeBehavior: "remove",
      expected: [
        // the notes aren't actually deleted, they just go past the clip bounds:
        0, 0.5, 1, 1.5, 2
      ],
    },
    {
      notes: [
        { pitch: 1, start: 0 },
        { pitch: 2, start: 0 },
        { pitch: 3, start: 0 },
        { pitch: 4, start: 0 },
        { pitch: 5, start: 0 },
      ],
      range: 2,
      amount: 1,
      anchor: "min",
      unlockEnd: false,
      edgeBehavior: "remove",
      expected: [
        { start: 0, duration: 1 },
        { start: 0.5, duration: 0.5 },
      ],
    },
    {
      notes: [
        { pitch: 1, start: 1 },
        { pitch: 2, start: 1 },
        { pitch: 3, start: 1 },
        { pitch: 4, start: 1 },
        { pitch: 5, start: 1 },
      ],
      range: 1,
      amount: -1.5,
      anchor: "min",
      unlockEnd: false,
      edgeBehavior: "remove",
      expected: [
        // the notes aren't actually deleted, they just go past the clip bounds:
        // 1, 0.5, 0, -0.5, -1
        { start: 1, duration: 1 },
        { start: 0.625, duration: 1.375 },
        { start: 0.25, duration: 1.75 },
        { start: -0.125, duration: 2.125 },
        { start: -0.5, duration: 2.5 },
      ],
    },
    {
      notes: [
        { pitch: 1, start: 0 },
        { pitch: 2, start: 0 },
        { pitch: 3, start: 0 },
        { pitch: 4, start: 0 },
        { pitch: 5, start: 0 },
      ],
      clip: { start: 0, end: 1 },
      range: 1.5,
      amount: 1,
      anchor: "min",
      unlockEnd: true,
      edgeBehavior: "rotate",
      expected: [
        0, 0.375, 0.75, 0.125, 0.5,
      ],
    },
    {
      notes: [
        { pitch: 1, start: 0 },
        { pitch: 2, start: 0 },
        { pitch: 3, start: 0 },
        { pitch: 4, start: 0 },
        { pitch: 5, start: 0 },
      ],
      range: 1.5,
      amount: 1,
      anchor: "min",
      unlockEnd: false,
      edgeBehavior: "rotate",
      expected: [
        { start: 0, duration: 1 },
        { start: 0.375, duration: 0.625 },
        { start: 0.75, duration: 0.25 },
        { start: 0.125, duration: 0.875 },
        { start: 0.5, duration: 0.5 },
      ],
    },
    {
      notes: [
        { pitch: 1, start: 1 },
        { pitch: 2, start: 1 },
        { pitch: 3, start: 1 },
        { pitch: 4, start: 1 },
        { pitch: 5, start: 1 },
      ],
      range: 1,
      amount: -1.5,
      anchor: "min",
      unlockEnd: false,
      edgeBehavior: "rotate",
      expected: [
        { start: 1, duration: 1 },
        { start: 0.625, duration: 1.375 },
        { start: 0.25, duration: 1.75 },
        { start: 1.875, duration: 0.125 },
        { start: 1.5, duration: 0.5 },
      ],
    },
    // TODO:
    // duration (end time) versions of all the above tests
  ]);
});
