name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12, 14]

    name: Node.js ${{ matrix.node-version }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build and test
      run: |
        npm ci
        npm run ci
      env:
        CI: true
